# Generated by Django 3.0.7 on 2020-07-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=200),
            preserve_default=False,
        ),
    ]
